[package]
name = "rustless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "1.3", features = ["full"] }
tokio = { version = "1", features = ["full"] }
